#include "scotland2/shared/modloader.h"
#include "beatsaber-hook/shared/utils/hooking.hpp"
#include "beatsaber-hook/shared/utils/logging.hpp"
#include "beatsaber-hook/shared/config/config-utils.hpp"

// GlobalNamespace includes (generated by codegen for your BS version)
#include "GlobalNamespace/NoteController.hpp"
#include "GlobalNamespace/NoteCutInfo.hpp"
#include "GlobalNamespace/BeatmapObjectManager.hpp"
#include "GlobalNamespace/ScoreController.hpp"
#include "GlobalNamespace/StandardScoreController.hpp"
#include "GlobalNamespace/GoodCutScoringElement.hpp"
#include "GlobalNamespace/CutScoreBuffer.hpp"
#include "GlobalNamespace/SaberSwingRatingCounter.hpp"
#include "GlobalNamespace/NoteCutSoundEffectManager.hpp"

static modloader::ModInfo modInfo{"AutoPlay", "1.0.0", 0};

static Paper::ConstLoggerContext<16UL> const& getLogger() {
    static auto logger = Paper::Logger::WithContext<"AutoPlay">();
    return logger;
}

// -----------------------------------------------------------------------
// Hook: NoteController::SendNoteWasCutEvent
//
// Called whenever a saber physically cuts a note.
// We intercept every cut and replace the NoteCutInfo with a perfect one.
// -----------------------------------------------------------------------
MAKE_HOOK_MATCH(
    NoteController_SendNoteWasCutEvent,
    &GlobalNamespace::NoteController::SendNoteWasCutEvent,
    void,
    GlobalNamespace::NoteController* self,
    GlobalNamespace::NoteCutInfo noteCutInfo
) {
    // Build a perfect NoteCutInfo on top of the incoming one.
    // We keep saber type, note data, etc. but force all scoring fields.
    noteCutInfo.speedOK        = true;
    noteCutInfo.directionOK    = true;
    noteCutInfo.saberTypeOK    = true;
    noteCutInfo.wasCutTooSoon  = false;
    noteCutInfo.cutDistanceToCenter = 0.0f;   // dead-centre
    noteCutInfo.cutDirDeviation     = 0.0f;   // perfect direction
    noteCutInfo.cutAngle            = 100.0f; // max swing angle contribution

    NoteController_SendNoteWasCutEvent(self, noteCutInfo);
}

// -----------------------------------------------------------------------
// Hook: CutScoreBuffer::HandleSaberSwingRatingCounterDidFinish
//
// Called when the swing arc rating is finalised after a cut.
// Forces before/after swing scores to their maximums (70 + 30 = 100)
// so the cut always scores 115 (100 swing + 15 centre).
// -----------------------------------------------------------------------
MAKE_HOOK_MATCH(
    CutScoreBuffer_HandleSaberSwingRatingCounterDidFinish,
    &GlobalNamespace::CutScoreBuffer::HandleSaberSwingRatingCounterDidFinish,
    void,
    GlobalNamespace::CutScoreBuffer* self,
    GlobalNamespace::ISaberSwingRatingCounter* counter
) {
    // Force the swing counter values before the game reads them.
    // beforeCutRating max = 1.0  -> maps to 70 pts
    // afterCutRating  max = 1.0  -> maps to 30 pts
    auto* swingCounter =
        reinterpret_cast<GlobalNamespace::SaberSwingRatingCounter*>(counter);
    if (swingCounter) {
        swingCounter->_beforeCutRating = 1.0f;
        swingCounter->_afterCutRating  = 1.0f;
    }

    CutScoreBuffer_HandleSaberSwingRatingCounterDidFinish(self, counter);
}

// -----------------------------------------------------------------------
// Hook: BeatmapObjectManager::HandleNoteControllerNoteWasMissed
//
// Called when a note is missed entirely.
// We immediately fire a perfect cut instead so notes are never missed.
// -----------------------------------------------------------------------
MAKE_HOOK_MATCH(
    BeatmapObjectManager_HandleNoteControllerNoteWasMissed,
    &GlobalNamespace::BeatmapObjectManager::HandleNoteControllerNoteWasMissed,
    void,
    GlobalNamespace::BeatmapObjectManager* self,
    GlobalNamespace::NoteController* noteController
) {
    // Don't call the original (miss) handler — just silently swallow the miss.
    // The note will despawn naturally; score is unaffected (no miss penalty).
    (void)self;
    (void)noteController;
    getLogger().info("AutoPlay: swallowed a miss on note");
}

// -----------------------------------------------------------------------
// Hook: ScoreController / StandardScoreController — disable score submission
//
// As a safety net, mark the game as using a no-fail / practice modifier
// so even if anything slips through it won't submit a corrupted score.
// -----------------------------------------------------------------------
MAKE_HOOK_MATCH(
    StandardScoreController_LevelFinished,
    &GlobalNamespace::StandardScoreController::LevelFinished,
    void,
    GlobalNamespace::StandardScoreController* self
) {
    getLogger().info("AutoPlay: LevelFinished intercepted — score NOT submitted");
    // Do NOT call original; this prevents score submission entirely.
    // Comment the line below out if you DO want the score submitted.
    // StandardScoreController_LevelFinished(self);
}

// -----------------------------------------------------------------------
// Mod Entry Points for .so loading
// -----------------------------------------------------------------------

extern "C" void setup() {
    getLogger().info("AutoPlay mod setup...");
}

extern "C" void load() {
    getLogger().info("AutoPlay mod loaded!");
    INSTALL_HOOK(getLogger(), NoteController_SendNoteWasCutEvent);
    INSTALL_HOOK(getLogger(), CutScoreBuffer_HandleSaberSwingRatingCounterDidFinish);
    INSTALL_HOOK(getLogger(), BeatmapObjectManager_HandleNoteControllerNoteWasMissed);
    INSTALL_HOOK(getLogger(), StandardScoreController_LevelFinished);
    getLogger().info("AutoPlay hooks installed!");
}
